### ISSUE TITLE
Update Tech Stack

### ISSUE THREAD

**Issue by sammaji** [samyabrata-maji/serious-portfolio#1]
1. Go to `data/project.data.ts` and update TECH_STACK object as per the instructions.
2. Checkout my [github](https://github.com/samyabrata-maji) for details on my tech stack (don't include `application` stack)
3. For every tech, create a new entry in `TECH_STACK`. Taking react as example:
``` javascript
const TECH_STACK = {
  react: {
    title: "React",
    icon: ""
  }
}
```
4. Go to [devicons](https://devicon.dev/) and and copy the class name (here "devicon-react-original") and remove the "devicons-" from the name and add that to icon property in `TECH_STACK`. Example:

<img width="809" alt="Screenshot 2023-01-29 121627" src="https://user-images.githubusercontent.com/116789799/215310111-71c65fe4-6fbc-45c4-a1fa-9672978a693f.png">

```javascript
const TECH_STACK = {
  react: {
    title: "React",
    icon: "react-original" // <--
  }
}
```
5. Also add firebase, next, svelte, sveltekit, tailwind and figma to my tech stack. remove html/css from tech stack

**Comment by sammaji** [comment]
Do you want to work on this @RockingSNP ? Let me know quickly.

**Comment by RockingSNP** [comment]
**_I have send you the pr make sure to check it and let me know,if there is any mistake_**
