### ISSUE TITLE
Add License to this project

### ISSUE THREAD

**Issue by sammaji** [samyabrata-maji/serious-portfolio#11]
Add a `LICENSE.md` file to this project containing MIT license

**Comment by souradip2k4** [comment]
Hey, I may fix this issue.

**Comment by sammaji** [comment]
Sure go ahead

**Comment by sammaji** [comment]
Hey @Souradip2022 , the `LICENSE.md` file accidentally got deleted while I was experimenting with GitHub rules. Can you please add it again?

**Comment by souradip2k4** [comment]
Of course I will add it
