### ISSUE TITLE
💡 [REQUEST] - Issues with links and clickable orange backgrounds on the portfolio

### ISSUE THREAD

**Issue by kaua-nasc** [samyabrata-maji/serious-portfolio#22]
### Summary

The requested feature aims to improve the user experience by addressing two specific issues in a portfolio website:

1. Opening links in a new tab/window: The feature involves adding the target="_blank" attribute to external links within the portfolio. This allows users to click on these links without losing the context of the portfolio website, as the linked content will open in a new browser tab or window. By implementing this feature, users can easily navigate external resources while keeping the portfolio accessible for reference.
2. Clickable orange backgrounds: The feature focuses on making the entire orange background of certain elements in the portfolio clickable as a link. Currently, only the text within these elements is clickable, which can be confusing for visitors. By extending the clickable area to include the orange background, users will have a more intuitive experience and be able to access related content more easily.

### Example

`<a href="https://www.example.com" target="_blank">Click here</a>`

In this example, the link will redirect the user to "https://www.example.com/", and upon clicking it, a new tab or browser window will open to display the content of the link, while keeping the current site open for reference.

### Impacts

When considering the drawbacks or potential impacts of the feature request, there are a few aspects to take into account:

1. Usability for users who prefer opening links in the same tab/window: By implementing the target="_blank" attribute universally for external links, it may disrupt the browsing experience for users who prefer opening links in the same tab or window. Opening every external link in a new tab or window can lead to cluttered browser environments and make it harder for users to manage their browsing sessions.
2. Mobile and touch device considerations: Opening links in new tabs or windows may have different behaviors on mobile devices and touchscreens. Users on such devices often rely on gestures or specific browser features to navigate between tabs or windows, and automatically opening new tabs for every external link might not align well with these interaction patterns.
3. Accessibility implications: The use of new tabs or windows can have accessibility implications, particularly for users who rely on assistive technologies or have specific needs related to tab or window management. It's essential to consider the impact on users with disabilities and ensure that the feature request doesn't introduce barriers to their browsing experience.
4. User expectations and consistency: The decision to open links in new tabs or windows should align with user expectations and established conventions. While it can be useful in certain scenarios, it's important to maintain consistency with standard browsing behavior to avoid confusing or surprising users who are accustomed to links opening in the same tab.

**Comment by sammaji** [comment]
Since most of the links are just links to external projects, I think it is better to open them in new tabs. Its also best practice to add `rel="noopener noreferrer"` to safeguard against cross-site attacks.

And yes I agree we should increase the clickable area for better user experience.

Would you like to contribute?

**Comment by kaua-nasc** [comment]
if you don't see any problem I would like to contribute

**Comment by sammaji** [comment]
Yeah go ahead.
