### ISSUE TITLE
[DOCS] code_of_conduct.md

### ISSUE THREAD

**Issue by sammaji** [samyabrata-maji/serious-portfolio#4]

**Comment by the-amazing-atharva** [comment]
Working on it 
Do assign it to me

**Comment by sammaji** [comment]
Hey @the-amazing-atharva, the `CODE_OF_CONDUCT.md` file accidentally got removed when I was experimenting with GitHub rules. Can you please add it again?

**Comment by the-amazing-atharva** [comment]
Sure!
